### ISSUE TITLE
Daemonset descibe needed in snapshot tool

### ISSUE THREAD

**Issue by mew2057** [IBM/ibm-spectrum-scale-csi#144]
Today the snapshot tool is  missing a describe  of the Daemon Set

```kubectl describe ds ibm-spectrum-scale-csi -n ibm-spectrum-scale-csi-driver```

**Describe the solution you'd like**
Add the describe to the snapshot tool for the 

```kubectl describe ds ibm-spectrum-scale-csi -n ibm-spectrum-scale-csi-driver```

**Comment by michiboo** [comment]
Hi Can I have a go at this issue?

**Comment by mew2057** [comment]
Hi, sure. It looks like you're not  an ibmer, so we  do have a  contributor's agreement that needs to be  followed: https://github.com/IBM/ibm-spectrum-scale-csi/blob/master/CONTRIBUTING.md

@aspalazz Is there anything  missing from this contributing readme?

**Comment by aspalazz** [comment]
@michiboo - great; we really appreciate the offer and are definitely open to having others jump in and contribute to our CSI code.  As @mew2057 mentioned, go ahead and read through the contributor's agreement, paying special attention to the sign-off and author lines.  We've tried to make it as lightweight as possible.  Let us know if you have any questions.  If you are contributing in the form of a company or organization instead of merely an individual, please let us know.  Thanks!
