### ISSUE TITLE
NodeSelector Needs to be Commented

### ISSUE THREAD

**Issue by tristan-le** [IBM/ibm-spectrum-scale-csi#237]
**Bug Description**
In documentation, we are asked to use this command "curl -O https://raw.githubusercontent.com/IBM/ibm-spectrum-scale-csi/v2.0.0/operator/deploy/crds/csiscaleoperators.csi.ibm.com_cr.yaml". The CR yaml has all NodeSelector sections uncommented, when they should be commented.

<img width="695" alt="image" src="https://user-images.githubusercontent.com/66130947/84449496-74571e80-ac02-11ea-8f62-67c280380b60.png">

**To Reproduce**
The CR yaml can be viewed by using the curl command to pull the yaml to system or at the link the curl is using.

**Expected behavior**
All NodeSelector sections should be commented.

**Environment**
Any

**Additional context**
None

**Comment by Jainbrt** [comment]
@tristan-le yes, they have been un-commented explicitly because admin should set label going forward before CSI installation and it is important because unless you have label set, upgrade process of spectrumscale on worker nodes is difficult.

**Comment by gandhisanjayv** [comment]
we should add node selectors steps in per-requisits.

**Comment by smitaraut** [comment]
I think these should be commented as node selectors are not mandatory. We can add recommendation about it in pre-req

**Comment by girishshankaran** [comment]
Hi Tristan,

This issue is addressed by adding the following text in this topic:
https://rtpdoc01.rtp.raleigh.ibm.com:9443/kc/STXKQY_CSI_review/com.ibm.spectrum.scale.csi.v2r00.doc/bl1csi_instal_prereq.html

Label the Kubernetes worker nodes where IBM Spectrum Scale client is installed and where IBM Spectrum Scale Container Storage Interface driver should run, as follows:
kubectl label node node1 scale=true --overwrite=true

**Comment by deeghuge** [comment]
Hi Smita, Without mandatory node selector we will have at least following issues
- Spectrum Scale maintenance(shutdown, unmount, upgrade) is not possible
- if new nodes being added to k8s, CSI Driver will start automatically
