### ISSUE TITLE
implement leader flagging for HA of attacher and provisioner

### ISSUE THREAD

**Issue by gandhisanjayv** [IBM/ibm-spectrum-scale-csi#65]
**Is your feature request related to a problem? Please describe.**
it will  remove single point of failure of provisioner and attacher. 
solve following upgrade issue.
what should be order of upgrading pods?  should it upgrade driver pods which are not running on provisioner/attacher nodes should be upgraded first?  this is to ensure that csi driver is partially functional if driver pod upgrade fails

**Describe the solution you'd like**
Suggested by Evan
https://github.com/kubernetes-csi/external-attacher#important-optional-arguments-that-are-highly-recommended-to-be-used
**Describe alternatives you've considered**

**Additional context**

**Comment by mew2057** [comment]
Right now the upgrade is deploying a template in a predefined order:
https://github.com/IBM/ibm-spectrum-scale-csi/blob/55112a862c5f61e0c8800e3b58201d8dc0fc1189/operator/roles/csi-scale/tasks/main.yml#L78

This  is likely a change to  the templates for the DaemonSets and StatefulSets.  I'm going to target this for Driver and Operator, because a change in the Driver is going to necessitate an operator change.

**Comment by madhuthorat** [comment]
This looks difficult to contain in CSI 2.5.0 release.

**Comment by deeghuge** [comment]
This is implemented and Tested hence closing. @gandhisanjayv please reopen if you disagree
