### ISSUE TITLE
Mount filesystem automatically, enable quota automatically

### ISSUE THREAD

**Issue by przem123** [IBM/ibm-spectrum-scale-csi#91]
Mount filesystem and enable quota automatically, especially for remote filesystem as they cannot be set locally to automount with mmchfs. Since you can perform mount/quota enablement with the GUI REST API, please add this functionality to the driver too.

**Comment by mew2057** [comment]
This seems like it might be able to be rolled into a general API improvement.

**Comment by deeghuge** [comment]
@przem123 , Few points 
1. The current scope of driver does not include the creation of filesystem and filesystem may be used for other purpose hence driver is not interfering the quota and automount configuration. 
2. There might be use case where only lightweight volumes are required in that case quota is required. 
3. Only primary filesystem is known at initialisation, other filesystem become known to driver only during volume creation. 

This is good improvement but due to above limitations we will defer it for future and fix It at appropriate time.

**Comment by deeghuge** [comment]
On other thought, I think CSI Driver is not right place for this requirement. 
Spectrum Scale should handle this.

**Comment by deeghuge** [comment]
Closing  since this is taken care as part of CNSA deployment where filesystem is created, Mounted and required default param is set(quota, filesetdf, SELinux config). Please reopen if required.
